### ISSUE TITLE
fix: consider `l10n.yaml`'s `output-class` parameter when generating `PhraseLocalizations` class

### ISSUE THREAD

**Issue by mugbug** [phrase/flutter_sdk_example#16]
## Summary

We use OTA feature from phrase on our project and we organize it as a monorepo, so we have multiple packages on the same project. For better code organization, we have split the .arb files and there is one for each package. Also aiming code organization, we customize the `AppLocalizations` class name on the packages using the `output-class` field from the `l10n.yaml` file, so we get a more contextual Localizations class.

## Problem

The issue is that the code generation tool from phrase used to generate the `PhraseLocalizations` class doesn't seem to consider this field when generating the code, causing some build erros.

## Proposal

As a solution, we could just start considering that the `AppLocalizations` may not have that exact name due to the `output-class` field being set.

So, in practice, instead of generating these classes:

```dart
class _PhraseLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> { /*...*/ }

class PhraseLocalizations extends AppLocalizations { /*...*/ }
```

We might have something like this

```dart
class _PhraseLocalizationsDelegate extends LocalizationsDelegate<OutputClassName> { /*...*/ }

class PhraseLocalizations extends OutputClassName { /*...*/ }
```

for a `l10n.yaml` file that looks like this

```yaml
arb-dir: lib/l10n

template-arb-file: pt-BR.arb

output-localization-file: app_localizations.dart

output-dir: lib/src/l10n/generated

synthetic-package: false

output-class: OutputClassName
```
